export const leaderBoardHomeMock = [
  {
    totalPoints: 9,
    totalGames: 3,
    name: 'Santos',
    totalVictories: 3,
    totalDraws: 0,
    totalLosses: 0,
    goalsFavor: 9,
    goalsOwn: 3,
    goalsBalance: 6,
    efficiency: '100.00'
  },
  {
    totalPoints: 7,
    totalGames: 3,
    name: 'Palmeiras',
    totalVictories: 2,
    totalDraws: 1,
    totalLosses: 0,
    goalsFavor: 10,
    goalsOwn: 5,
    goalsBalance: 5,
    efficiency: '77.78'
  },
  {
    totalPoints: 6,
    totalGames: 2,
    name: 'Corinthians',
    totalVictories: 2,
    totalDraws: 0,
    totalLosses: 0,
    goalsFavor: 6,
    goalsOwn: 1,
    goalsBalance: 5,
    efficiency: '100.00'
  },
  {
    totalPoints: 6,
    totalGames: 2,
    name: 'Grêmio',
    totalVictories: 2,
    totalDraws: 0,
    totalLosses: 0,
    goalsFavor: 4,
    goalsOwn: 1,
    goalsBalance: 3,
    efficiency: '100.00'
  },
  {
    totalPoints: 6,
    totalGames: 2,
    name: 'Real Brasília',
    totalVictories: 2,
    totalDraws: 0,
    totalLosses: 0,
    goalsFavor: 2,
    goalsOwn: 0,
    goalsBalance: 2,
    efficiency: '100.00'
  },
  {
    totalPoints: 4,
    totalGames: 2,
    name: 'São Paulo',
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 0,
    goalsFavor: 4,
    goalsOwn: 1,
    goalsBalance: 3,
    efficiency: '66.67'
  },
  {
    totalPoints: 4,
    totalGames: 3,
    name: 'Internacional',
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 4,
    goalsOwn: 6,
    goalsBalance: -2,
    efficiency: '44.44'
  },
  {
    totalPoints: 4,
    totalGames: 4,
    name: 'Minas Brasília',
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 2,
    goalsFavor: 4,
    goalsOwn: 6,
    goalsBalance: -2,
    efficiency: '33.33'
  },
  {
    totalPoints: 4,
    totalGames: 3,
    name: 'Botafogo',
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 2,
    goalsOwn: 4,
    goalsBalance: -2,
    efficiency: '44.44'
  },
  {
    totalPoints: 3,
    totalGames: 2,
    name: 'Ferroviária',
    totalVictories: 1,
    totalDraws: 0,
    totalLosses: 1,
    goalsFavor: 3,
    goalsOwn: 2,
    goalsBalance: 1,
    efficiency: '50.00'
  },
  {
    totalPoints: 3,
    totalGames: 3,
    name: 'Napoli-SC',
    totalVictories: 0,
    totalDraws: 3,
    totalLosses: 0,
    goalsFavor: 2,
    goalsOwn: 2,
    goalsBalance: 0,
    efficiency: '33.33'
  },
  {
    totalPoints: 2,
    totalGames: 3,
    name: 'Cruzeiro',
    totalVictories: 0,
    totalDraws: 2,
    totalLosses: 1,
    goalsFavor: 3,
    goalsOwn: 4,
    goalsBalance: -1,
    efficiency: '22.22'
  },
  {
    totalPoints: 1,
    totalGames: 2,
    name: 'Flamengo',
    totalVictories: 0,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 1,
    goalsOwn: 2,
    goalsBalance: -1,
    efficiency: '16.67'
  },
  {
    totalPoints: 1,
    totalGames: 3,
    name: 'Avaí/Kindermann',
    totalVictories: 0,
    totalDraws: 1,
    totalLosses: 2,
    goalsFavor: 3,
    goalsOwn: 7,
    goalsBalance: -4,
    efficiency: '11.11'
  },
  {
    totalPoints: 0,
    totalGames: 3,
    name: 'São José-SP',
    totalVictories: 0,
    totalDraws: 0,
    totalLosses: 3,
    goalsFavor: 2,
    goalsOwn: 5,
    goalsBalance: -3,
    efficiency: '0.00'
  },
  {
    totalPoints: 0,
    totalGames: 3,
    name: 'Bahia',
    totalVictories: 0,
    totalDraws: 0,
    totalLosses: 3,
    goalsFavor: 0,
    goalsOwn: 4,
    goalsBalance: -4,
    efficiency: '0.00'
  }
]

export const leaderBoardAwayMock = [
  {
    totalPoints: 6,
    totalGames: 2,
    name: 'Palmeiras',
    totalVictories: 2,
    totalDraws: 0,
    totalLosses: 0,
    goalsFavor: 7,
    goalsOwn: 0,
    goalsBalance: 7,
    efficiency: '100.00'
  },
  {
    totalPoints: 6,
    totalGames: 3,
    name: 'Corinthians',
    totalVictories: 2,
    totalDraws: 0,
    totalLosses: 1,
    goalsFavor: 6,
    goalsOwn: 2,
    goalsBalance: 4,
    efficiency: '66.67'
  },
  {
    totalPoints: 6,
    totalGames: 2,
    name: 'Internacional',
    totalVictories: 2,
    totalDraws: 0,
    totalLosses: 0,
    goalsFavor: 3,
    goalsOwn: 0,
    goalsBalance: 3,
    efficiency: '100.00'
  },
  {
    totalPoints: 6,
    totalGames: 2,
    name: 'São José-SP',
    totalVictories: 2,
    totalDraws: 0,
    totalLosses: 0,
    goalsFavor: 3,
    goalsOwn: 1,
    goalsBalance: 2,
    efficiency: '100.00'
  },
  {
    totalPoints: 4,
    totalGames: 3,
    name: 'São Paulo',
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 5,
    goalsOwn: 5,
    goalsBalance: 0,
    efficiency: '44.44'
  },
  {
    totalPoints: 4,
    totalGames: 4,
    name: 'Cruzeiro',
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 2,
    goalsFavor: 6,
    goalsOwn: 7,
    goalsBalance: -1,
    efficiency: '33.33'
  },
  {
    totalPoints: 4,
    totalGames: 3,
    name: 'Real Brasília',
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 3,
    goalsOwn: 4,
    goalsBalance: -1,
    efficiency: '44.44'
  },
  {
    totalPoints: 4,
    totalGames: 3,
    name: 'Grêmio',
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 5,
    goalsOwn: 7,
    goalsBalance: -2,
    efficiency: '44.44'
  },
  {
    totalPoints: 4,
    totalGames: 4,
    name: 'Ferroviária',
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 2,
    goalsFavor: 4,
    goalsOwn: 6,
    goalsBalance: -2,
    efficiency: '33.33'
  },
  {
    totalPoints: 4,
    totalGames: 3,
    name: 'Flamengo',
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 1,
    goalsOwn: 3,
    goalsBalance: -2,
    efficiency: '44.44'
  },
  {
    totalPoints: 3,
    totalGames: 2,
    name: 'Avaí/Kindermann',
    totalVictories: 1,
    totalDraws: 0,
    totalLosses: 1,
    goalsFavor: 1,
    goalsOwn: 1,
    goalsBalance: 0,
    efficiency: '50.00'
  },
  {
    totalPoints: 2,
    totalGames: 2,
    name: 'Santos',
    totalVictories: 0,
    totalDraws: 2,
    totalLosses: 0,
    goalsFavor: 3,
    goalsOwn: 3,
    goalsBalance: 0,
    efficiency: '33.33'
  },
  {
    totalPoints: 2,
    totalGames: 2,
    name: 'Bahia',
    totalVictories: 0,
    totalDraws: 2,
    totalLosses: 0,
    goalsFavor: 2,
    goalsOwn: 2,
    goalsBalance: 0,
    efficiency: '33.33'
  },
  {
    totalPoints: 1,
    totalGames: 2,
    name: 'Minas Brasília',
    totalVictories: 0,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 1,
    goalsOwn: 3,
    goalsBalance: -2,
    efficiency: '16.67'
  },
  {
    totalPoints: 1,
    totalGames: 4,
    name: 'Napoli-SC',
    totalVictories: 0,
    totalDraws: 1,
    totalLosses: 3,
    goalsFavor: 2,
    goalsOwn: 11,
    goalsBalance: -9,
    efficiency: '8.33'
  },
  {
    totalPoints: 0,
    totalGames: 2,
    name: 'Botafogo',
    totalVictories: 0,
    totalDraws: 0,
    totalLosses: 2,
    goalsFavor: 1,
    goalsOwn: 4,
    goalsBalance: -3,
    efficiency: '0.00'
  }
]

export const leaderBoardMock = [
  {
    totalPoints: 13,
    totalGames: 5,
    name: 'Palmeiras',
    totalVictories: 4,
    totalDraws: 1,
    totalLosses: 0,
    goalsFavor: 17,
    goalsOwn: 5,
    goalsBalance: 12,
    efficiency: '86.67'
  },
  {
    totalPoints: 12,
    totalGames: 5,
    name: 'Corinthians',
    totalVictories: 4,
    totalDraws: 0,
    totalLosses: 1,
    goalsFavor: 12,
    goalsOwn: 3,
    goalsBalance: 9,
    efficiency: '80.00'
  },
  {
    totalPoints: 11,
    totalGames: 5,
    name: 'Santos',
    totalVictories: 3,
    totalDraws: 2,
    totalLosses: 0,
    goalsFavor: 12,
    goalsOwn: 6,
    goalsBalance: 6,
    efficiency: '73.33'
  },
  {
    totalPoints: 10,
    totalGames: 5,
    name: 'Grêmio',
    totalVictories: 3,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 9,
    goalsOwn: 8,
    goalsBalance: 1,
    efficiency: '66.67'
  },
  {
    totalPoints: 10,
    totalGames: 5,
    name: 'Internacional',
    totalVictories: 3,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 7,
    goalsOwn: 6,
    goalsBalance: 1,
    efficiency: '66.67'
  },
  {
    totalPoints: 10,
    totalGames: 5,
    name: 'Real Brasília',
    totalVictories: 3,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 5,
    goalsOwn: 4,
    goalsBalance: 1,
    efficiency: '66.67'
  },
  {
    totalPoints: 8,
    totalGames: 5,
    name: 'São Paulo',
    totalVictories: 2,
    totalDraws: 2,
    totalLosses: 1,
    goalsFavor: 9,
    goalsOwn: 6,
    goalsBalance: 3,
    efficiency: '53.33'
  },
  {
    totalPoints: 7,
    totalGames: 6,
    name: 'Ferroviária',
    totalVictories: 2,
    totalDraws: 1,
    totalLosses: 3,
    goalsFavor: 7,
    goalsOwn: 8,
    goalsBalance: -1,
    efficiency: '38.89'
  },
  {
    totalPoints: 6,
    totalGames: 5,
    name: 'São José-SP',
    totalVictories: 2,
    totalDraws: 0,
    totalLosses: 3,
    goalsFavor: 5,
    goalsOwn: 6,
    goalsBalance: -1,
    efficiency: '40.00'
  },
  {
    totalPoints: 6,
    totalGames: 7,
    name: 'Cruzeiro',
    totalVictories: 1,
    totalDraws: 3,
    totalLosses: 3,
    goalsFavor: 9,
    goalsOwn: 11,
    goalsBalance: -2,
    efficiency: '28.57'
  },
  {
    totalPoints: 5,
    totalGames: 5,
    name: 'Flamengo',
    totalVictories: 1,
    totalDraws: 2,
    totalLosses: 2,
    goalsFavor: 2,
    goalsOwn: 5,
    goalsBalance: -3,
    efficiency: '33.33'
  },
  {
    totalPoints: 5,
    totalGames: 6,
    name: 'Minas Brasília',
    totalVictories: 1,
    totalDraws: 2,
    totalLosses: 3,
    goalsFavor: 5,
    goalsOwn: 9,
    goalsBalance: -4,
    efficiency: '27.78'
  },
  {
    totalPoints: 4,
    totalGames: 5,
    name: 'Avaí/Kindermann',
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 3,
    goalsFavor: 4,
    goalsOwn: 8,
    goalsBalance: -4,
    efficiency: '26.67'
  },
  {
    totalPoints: 4,
    totalGames: 5,
    name: 'Botafogo',
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 3,
    goalsFavor: 3,
    goalsOwn: 8,
    goalsBalance: -5,
    efficiency: '26.67'
  },
  {
    totalPoints: 4,
    totalGames: 7,
    name: 'Napoli-SC',
    totalVictories: 0,
    totalDraws: 4,
    totalLosses: 3,
    goalsFavor: 4,
    goalsOwn: 13,
    goalsBalance: -9,
    efficiency: '19.05'
  },
  {
    totalPoints: 2,
    totalGames: 5,
    name: 'Bahia',
    totalVictories: 0,
    totalDraws: 2,
    totalLosses: 3,
    goalsFavor: 2,
    goalsOwn: 6,
    goalsBalance: -4,
    efficiency: '13.33'
  }
]
